name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install the project so tests can import deepr
          python -m pip install -e .
          # install test/runtime deps required by tests
          python -m pip install pytest httpx respx typer pydantic pytest-asyncio anyio
      - name: Run tests
        run: |
          PYTHONPATH=. pytest -q
